name: Go Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build Go Application and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.0

      - name: Remove Old Deployment in DigitalOcean 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          key_type: rsa
          script: |
            set -e
            echo "Removing old deployment..."
            ssh ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }} "cd /tmp/my-app && rm -rf *"

      - name: Copy Application Files to Target System
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ./*
          target: /tmp/my-app 

      - name: Build Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          key_type: rsa
          script: |
            set -e
            cd /tmp/my-app

            # Stop and remove containers with specific labels
            docker stop my-database-app || true
            docker rm my-database-app || true

            # Remove images with specific labels
            docker rmi my-database-app || true

            # Build and run Docker image with encapsulated environment
            docker build -t my-database-app .
            docker run -d --name my-database-app --network my-network -p 8080:8080 my-database-app
